//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityTravel.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CityTravel.Translations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AboutUs.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AboutUsText.
        /// </summary>
        public static string AboutUsText {
            get {
                return ResourceManager.GetString("AboutUsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add route.
        /// </summary>
        public static string AddRoute {
            get {
                return ResourceManager.GetString("AddRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add stop.
        /// </summary>
        public static string AddStop {
            get {
                return ResourceManager.GetString("AddStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdressError.
        /// </summary>
        public static string AdressError {
            get {
                return ResourceManager.GetString("AdressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильное имя пользователя или пароль.
        /// </summary>
        public static string AuthenticationError {
            get {
                return ResourceManager.GetString("AuthenticationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChooseCategory.
        /// </summary>
        public static string ChooseCategory {
            get {
                return ResourceManager.GetString("ChooseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChooseCategoryError.
        /// </summary>
        public static string ChooseCategoryError {
            get {
                return ResourceManager.GetString("ChooseCategoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сomplaint.
        /// </summary>
        public static string Complaint {
            get {
                return ResourceManager.GetString("Complaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CooperationPurpose.
        /// </summary>
        public static string CooperationPurpose {
            get {
                return ResourceManager.GetString("CooperationPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Hrn.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string EndPoint {
            get {
                return ResourceManager.GetString("EndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter address.
        /// </summary>
        public static string EnterAddress {
            get {
                return ResourceManager.GetString("EnterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnterLocation.
        /// </summary>
        public static string EnterLocation {
            get {
                return ResourceManager.GetString("EnterLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [en]FieldsRequired.
        /// </summary>
        public static string FieldsRequired {
            get {
                return ResourceManager.GetString("FieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FindRoute.
        /// </summary>
        public static string FindRoute {
            get {
                return ResourceManager.GetString("FindRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to кm.
        /// </summary>
        public static string Kilometr {
            get {
                return ResourceManager.GetString("Kilometr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MakeRoute.
        /// </summary>
        public static string MakeRoute {
            get {
                return ResourceManager.GetString("MakeRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string Metres {
            get {
                return ResourceManager.GetString("Metres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metro.
        /// </summary>
        public static string Metro {
            get {
                return ResourceManager.GetString("Metro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModelEmail.
        /// </summary>
        public static string ModelEmail {
            get {
                return ResourceManager.GetString("ModelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModelMessage.
        /// </summary>
        public static string ModelMessage {
            get {
                return ResourceManager.GetString("ModelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModelName.
        /// </summary>
        public static string ModelName {
            get {
                return ResourceManager.GetString("ModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money.
        /// </summary>
        public static string Money {
            get {
                return ResourceManager.GetString("Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at the stop called.
        /// </summary>
        public static string OnStop {
            get {
                return ResourceManager.GetString("OnStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opinion.
        /// </summary>
        public static string Opinion {
            get {
                return ResourceManager.GetString("Opinion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partnership.
        /// </summary>
        public static string Partnership {
            get {
                return ResourceManager.GetString("Partnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grn.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintRoute.
        /// </summary>
        public static string PrintRoute {
            get {
                return ResourceManager.GetString("PrintRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessingError.
        /// </summary>
        public static string ProcessingError {
            get {
                return ResourceManager.GetString("ProcessingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CityTravel.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose.
        /// </summary>
        public static string Purpose {
            get {
                return ResourceManager.GetString("Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefreshRelations.
        /// </summary>
        public static string RefreshRelations {
            get {
                return ResourceManager.GetString("RefreshRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredFields.
        /// </summary>
        public static string RequiredFields {
            get {
                return ResourceManager.GetString("RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ride on the shuttle until bus stop called.
        /// </summary>
        public static string RideUntil {
            get {
                return ResourceManager.GetString("RideUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoutesListCaption.
        /// </summary>
        public static string RoutesListCaption {
            get {
                return ResourceManager.GetString("RoutesListCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SbSInstruction.
        /// </summary>
        public static string SbSInstruction {
            get {
                return ResourceManager.GetString("SbSInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShuttleTransport.
        /// </summary>
        public static string ShuttleTransport {
            get {
                return ResourceManager.GetString("ShuttleTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShuttleTransportLabel.
        /// </summary>
        public static string ShuttleTransportLabel {
            get {
                return ResourceManager.GetString("ShuttleTransportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sit on.
        /// </summary>
        public static string Sit {
            get {
                return ResourceManager.GetString("Sit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string StartPoint {
            get {
                return ResourceManager.GetString("StartPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to temp.
        /// </summary>
        public static string temp {
            get {
                return ResourceManager.GetString("temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextVersion.
        /// </summary>
        public static string TextVersion {
            get {
                return ResourceManager.GetString("TextVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tramvay.
        /// </summary>
        public static string Tramvay {
            get {
                return ResourceManager.GetString("Tramvay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransportList.
        /// </summary>
        public static string TransportList {
            get {
                return ResourceManager.GetString("TransportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TroleyBus.
        /// </summary>
        public static string TroleyBus {
            get {
                return ResourceManager.GetString("TroleyBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong address.
        /// </summary>
        public static string ValidationAddress {
            get {
                return ResourceManager.GetString("ValidationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start and End coordinates are out of city boundaries.
        /// </summary>
        public static string ValidationCoords {
            get {
                return ResourceManager.GetString("ValidationCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong feedback parameters.
        /// </summary>
        public static string ValidationFeedback {
            get {
                return ResourceManager.GetString("ValidationFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouEnterWrongAdress.
        /// </summary>
        public static string YouEnterWrongAdress {
            get {
                return ResourceManager.GetString("YouEnterWrongAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouMustEnterMessage.
        /// </summary>
        public static string YouMustEnterMessage {
            get {
                return ResourceManager.GetString("YouMustEnterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouMustEnterName.
        /// </summary>
        public static string YouMustEnterName {
            get {
                return ResourceManager.GetString("YouMustEnterName", resourceCulture);
            }
        }
    }
}
